sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 050605/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true 050605/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "React-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-975758072381"
  bucket_path: "react-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

